adding:
  backend_config:
    connector: standard
    connector_config:
      scheme: http
      host: search
      port: 8983
      path: /
      core: sandbox
      skip_schema_check: false
      solr_version: ''
    index_empty_text_fields: false
    suppress_missing_languages: false
removing:
  dependencies:
    module:
      - search_api_pantheon
  backend_config:
    connector: pantheon
    connector_config:
      skip_schema_check: true
      solr_version: '8'
