name: pimentel-sandbox
recipe: pantheon
config:
  framework: drupal9
  site: pimentel-sandbox
  id: f81c4767-a713-4e8c-80c8-bc10f2433469
  composer_version: 2-latest
  php: '8.1'
  cache: false
  edge: false
  index: false
proxy:
  appserver_nginx:
    - pimentel-sandbox.lndo.site
    - sub.pimentel-sandbox.lndo.site
    - sub2.pimentel-sandbox.lndo.site
  # search:
  #   - search.pimentel-sandbox.site:8963
services:
  # search:
  #   type: solr:8
  #   portforward: true
  #   core: sandbox
  #   config:
  #     dir: .config/solr_8.x
  #     conf: solr/conf
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://pimentel-sandbox.lndo.site"
    build_as_root:
        #- rm -rf /etc/apt/keyrings/nodesource.gpg
        - apt update -y && apt install -y apt-transport-https
        - apt-get install -y ca-certificates curl gnupg
        - mkdir -p /etc/apt/keyrings
        - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
        - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
        - apt-get update && apt-get install nodejs -y
        - chown -R www-data /usr/lib/node_modules
        - chown -R www-data /usr/bin
        - npm install -g npm gulp-cli npx yarn
        - apt update -y
  database:
    portforward: 3307
  legacy_db:
    type: mysql
    portforward: 3308

tooling:
  npm:
    service: appserver
  node:
    service: appserver
  gulp:
    service: appserver
  yarn:
    service: appserver
  npx:
    service: appserver
  refresh:
    service: apperserver
    description: Corrects current issue between Devel & Pantheon after database refresh
    cmd: drush pmu devel -y && drush en devel -y && drush cr && drush cex -y