_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  components: 0
  config: 0
  config_translation: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  cookies: 0
  crop: 0
  ctools: 0
  custom_form: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  domain: 0
  domain_access: 0
  domain_access_logo: 0
  domain_alias: 0
  domain_config: 0
  domain_config_ui: 0
  domain_content: 0
  domain_source: 0
  domain_theme_switch: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  entity_reference_revisions: 0
  entity_usage: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  fontawesome: 0
  fontawesome_iconpicker_widget: 0
  fontawesome_media: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geofield: 0
  gin_toolbar: 0
  google_tag: 0
  help: 0
  history: 0
  htlf_alert: 0
  htlf_migrate: 0
  image: 0
  jquery_ui: 0
  jquery_ui_autocomplete: 0
  jquery_ui_menu: 0
  language: 0
  layout_discovery: 0
  leaflet: 0
  link: 0
  linkchecker: 0
  locale: 0
  media: 0
  media_library: 0
  menu_export: 0
  menu_link_content: 0
  menu_ui: 0
  menus_attribute: 0
  metatag: 0
  migrate: 0
  migrate_devel: 0
  migrate_drupal: 0
  migrate_drupal_d8: 0
  migrate_drupal_ui: 0
  migrate_plus: 0
  migrate_tools: 0
  migrate_upgrade: 0
  module_filter: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panels: 0
  paragraphs_browser: 0
  paragraphs_features: 0
  paragraphs_library: 0
  paragraphs_previewer: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  preprocess: 0
  quick_node_clone: 0
  redirect: 0
  rest: 0
  scheduled_transitions: 0
  scheduler: 0
  search: 0
  serialization: 0
  shortcut: 0
  shs: 0
  simple_sitemap: 0
  simplei: 0
  smart_date: 0
  svg_image: 0
  svg_image_field: 0
  symfony_debug: 0
  system: 0
  tamper: 0
  taxonomy: 0
  tb_megamenu: 0
  text: 0
  token: 0
  toolbar: 0
  total_control: 0
  tour: 0
  twig_debugger: 0
  twig_tweak: 0
  update: 0
  user: 0
  viewfield: 0
  views_bulk_edit: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_attachment: 0
  webform_image_select: 0
  webform_node: 0
  webform_options_custom: 0
  webform_options_limit: 0
  webform_scheduled_email: 0
  webform_schema: 0
  webform_share: 0
  webform_shortcuts: 0
  webform_submission_export_import: 0
  webform_submission_log: 0
  webform_templates: 0
  webform_ui: 0
  workflows: 0
  pathauto: 1
  password_policy: 10
  views: 10
  cookies_gtag: 11
  paragraphs: 11
  paragraphs_ee: 15
  standard: 1000
theme:
  claro: 0
  stable: 0
  tailwind: 0
  gin: 0
profile: standard
