_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  components: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  custom_form: 0
  datetime: 0
  dblog: 0
  domain: 0
  domain_access: 0
  domain_access_logo: 0
  domain_alias: 0
  domain_config: 0
  domain_config_ui: 0
  domain_content: 0
  domain_source: 0
  domain_theme_switch: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  entity_usage: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  help: 0
  history: 0
  image: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  menus_attribute: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  panels: 0
  paragraphs_library: 0
  path: 0
  path_alias: 0
  preprocess: 0
  search: 0
  shortcut: 0
  smart_date: 0
  symfony_debug: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  total_control: 0
  tour: 0
  twig_debugger: 0
  twig_tweak: 0
  update: 0
  user: 0
  viewfield: 0
  views_ui: 0
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  claro: 0
  stable: 0
  tailwind: 0
  gin: 0
profile: standard
