features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
contain_width: 0
theme_color: ''
olb_login: 'https://olb.bankbv.com/BBVOnline/uux.aspx'
split_login: 0
olb_enroll: 'https://olb.bankbv.com/BBV_AutoEnrollmentE2E/v2/enroll.html'
olb_forgot: 'https://olb.bankbv.com/BBVOnline/uux.aspx#/login/resetPasswordUsername'
olb_android: 'https://play.google.com/store/apps/details?id=com.q2e.themorrillandjanesbankandtrustcompany335309.mobile.production'
olb_apple: 'https://itunes.apple.com/us/app/morrill-janes-bank-trust-mobile/id882896556?mt=8&ign-mpt=uo%3D4'
custom_css: ".map-list .get-directions {\r\n  display: none;\r\n}\r\nlabel[for*=\"atm\"] {\r\n    text-transform: uppercase !important;\r\n}\r\n.title-bar-middle #mobile-logo > img {\r\n    min-height: unset;\r\n}"
head_javascript: ''
body_javascript: ''
footer_javascript: "if ($('.page-node-type-location .address').length) {\r\n  $.each($('.page-node-type-location .address'), function(){\r\n    const bankName = !$('.internal-page-banner h1').text().includes('ATM') ? $('title').text().split('|')[1] + ' - ' : '';\r\n    const address = $(this).find('.address-line1').text();\r\n    const city = $(this).find('.locality').text();\r\n    const state = $(this).find('.administrative-area').text();\r\n    const zip = $(this).find('.postal-code').text();\r\n    const country = $(this).find('.country').text();\r\n    const fullAddress = encodeURIComponent(`${bankName}${address}, ${city},${state}, ${zip} ${country}`);\r\n    const searchUrl = 'https://www.google.com/maps/search/?api=1&query=' + fullAddress;\r\n    const directionsUrl = 'https://www.google.com/maps/dir/?api=1&destination=' + fullAddress;\r\n\r\n    $(this).find('.button').attr('href', searchUrl);\r\n  })\r\n}"
header_height: '150'
