features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://logo/logo.svg'
favicon:
  use_default: 1
logo_footer:
  - '9185'
bank_name: 'HTLF Bank'
primary_color: '#212845'
secondary_color: '#1c3685'
test_color: '#1c3685'
